### ISSUE TITLE
Is only sorting possible?

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/DDS.Tools#115]
**Is your feature request related to a problem? Please describe.**
It's not a problem, rather a request. Would it be possible to just sort instead of converting? For example, it would be really cool to have the possibility to sort by height or width of an image.

**Describe the solution you'd like**
Add a sorting function.

**Describe alternatives you've considered**
None.

**Comment by BoBoBaSs84** [comment]
That sounds pretty plausible at first. That would probably be a different mode -> 'Sotring' ... in principle why not.

**Comment by Probotus** [comment]
The Playstation 2 emulator PCS2X offers the possibility to dump textures. The dump is quite simple, the textures are simply stored flat with a kind of GUID as a prefix as soon as they are loaded into memory.

This means that you have thousands of images in one directory. With a sorting function you could pre-sort the images by height and/or width before you edit or swap them.

**Comment by BoBoBaSs84** [comment]
It should be named grouping, since the images get grouped by size aka. width and height.😵
