### ISSUE TITLE
Help, I really need your program!!!

### ISSUE THREAD

**Issue by gameshark777** [BoBoBaSs84/DDS.Tools#50]
I'm a newbie and don't know how to turn your wonderful code into a program. But I really need this program because it is very useful when creating mods. Can you give me the full version of the program? Please...

**Comment by BoBoBaSs84** [comment]
I'm going to make a release ready (win-x64 binaries) so you don't need to compile the code for yourself.
See #51 

I will try to wright down some docs on how to use the tools.
See #52

**Comment by gameshark777** [comment]
> I'm going to make a release ready (win-x64 binaries) so you don't need to compile the code for yourself. See #51
> 
> I will try to wright down some docs on how to use the tools. See #52

I'll be looking forward to it. Tired of manually converting dds.... So you just launch the exe, select a folder and start converting.

PS When converting DDS to PNG, does your program remove alpha channels or save them as a separate file?
